spring:
  application:
    name: stock-market-dashboard

  security:
    user:
      name: user
      password: password

  datasource:
    url: jdbc:postgresql://localhost:5432/stock_db
    username: oluwabukolaomokehinde
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080