name: Java CI with Maven (JDK 23)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 23 (Early Access)
      - name: Setup JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23-ea'
          distribution: 'temurin'
          cache: 'maven'
          check-latest: true

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            target/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build and test
      - name: Build with Maven
        run: mvn -B clean package -DskipTests=true

      - name: Run Tests
        run: mvn test

      - name: Verify
        run: mvn verify

      # Optional: Code quality checks
      - name: Spotless check
        run: mvn spotless:check